// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBUxyu6mSSkkhs1Wxus982biCxqihlhKI',
    appId: '1:676358640512:web:82cda22fa0c6fcc0c12765',
    messagingSenderId: '676358640512',
    projectId: 'phishawareapp',
    authDomain: 'phishawareapp.firebaseapp.com',
    storageBucket: 'phishawareapp.firebasestorage.app',
    measurementId: 'G-HZ2LNFH5H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAknBn2WPnoCgb0zRmPdoQsfcp6USTNiog',
    appId: '1:676358640512:android:917cefdd88fe0d7ec12765',
    messagingSenderId: '676358640512',
    projectId: 'phishawareapp',
    storageBucket: 'phishawareapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9RVnuY1fJ85qjqo5-5gSTtHxRiuVOsI',
    appId: '1:676358640512:ios:7e99a025eb2ffbbbc12765',
    messagingSenderId: '676358640512',
    projectId: 'phishawareapp',
    storageBucket: 'phishawareapp.firebasestorage.app',
    iosBundleId: 'com.phishaware.phishaware',
  );
}
